name: Cestari-Inc
favicon: null
layout_spectrum: 0.16072957846336067
typography_spectrum: 0.9500682568177581
title: 'Cestari, Inc.'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.4543421610724181
  lightness: 0.24511250969953835
  saturation: 0.8742226622998714
  rhythmicContrast: 0.7233171509578824
purpose: []
